import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="starfield" aria-hidden>
          <div className="layer layer-1" />
          <div className="layer layer-2" />
          <div className="layer layer-3" />
        </div>
        <header className="navbar">
          <div className="navbar-inner">
            <span />
            <nav className="nav-links" aria-label="Primary">
              <a className="island-btn" href="#mission">Mission</a>
              <a className="island-btn" href="#vision">Vision</a>
              <a className="island-btn" href="#contact">Contact</a>
            </nav>
            <label htmlFor="nav-check" className="nav-toggle island-btn" aria-label="Open menu">☰</label>
          </div>
          <input id="nav-check" type="checkbox" />
          <div className="nav-menu">
            <nav className="flex flex-col gap-2" aria-label="Mobile">
              <a className="island-btn" href="#mission">Mission</a>
              <a className="island-btn" href="#vision">Vision</a>
              <a className="island-btn" href="#contact">Contact</a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
